// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/arflow_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/arflow_service.proto</summary>
  public static partial class ArflowServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/arflow_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArflowServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitjYWtlbGFiL2FyZmxvd19ncnBjL3YxL2FyZmxvd19zZXJ2aWNlLnByb3Rv",
            "EhZjYWtlbGFiLmFyZmxvd19ncnBjLnYxGjNjYWtlbGFiL2FyZmxvd19ncnBj",
            "L3YxL2NyZWF0ZV9zZXNzaW9uX3JlcXVlc3QucHJvdG8aNGNha2VsYWIvYXJm",
            "bG93X2dycGMvdjEvY3JlYXRlX3Nlc3Npb25fcmVzcG9uc2UucHJvdG8aM2Nh",
            "a2VsYWIvYXJmbG93X2dycGMvdjEvZGVsZXRlX3Nlc3Npb25fcmVxdWVzdC5w",
            "cm90bxo0Y2FrZWxhYi9hcmZsb3dfZ3JwYy92MS9kZWxldGVfc2Vzc2lvbl9y",
            "ZXNwb25zZS5wcm90bxowY2FrZWxhYi9hcmZsb3dfZ3JwYy92MS9nZXRfc2Vz",
            "c2lvbl9yZXF1ZXN0LnByb3RvGjFjYWtlbGFiL2FyZmxvd19ncnBjL3YxL2dl",
            "dF9zZXNzaW9uX3Jlc3BvbnNlLnByb3RvGjFjYWtlbGFiL2FyZmxvd19ncnBj",
            "L3YxL2pvaW5fc2Vzc2lvbl9yZXF1ZXN0LnByb3RvGjJjYWtlbGFiL2FyZmxv",
            "d19ncnBjL3YxL2pvaW5fc2Vzc2lvbl9yZXNwb25zZS5wcm90bxoyY2FrZWxh",
            "Yi9hcmZsb3dfZ3JwYy92MS9sZWF2ZV9zZXNzaW9uX3JlcXVlc3QucHJvdG8a",
            "M2Nha2VsYWIvYXJmbG93X2dycGMvdjEvbGVhdmVfc2Vzc2lvbl9yZXNwb25z",
            "ZS5wcm90bxoyY2FrZWxhYi9hcmZsb3dfZ3JwYy92MS9saXN0X3Nlc3Npb25z",
            "X3JlcXVlc3QucHJvdG8aM2Nha2VsYWIvYXJmbG93X2dycGMvdjEvbGlzdF9z",
            "ZXNzaW9uc19yZXNwb25zZS5wcm90bxozY2FrZWxhYi9hcmZsb3dfZ3JwYy92",
            "MS9zYXZlX2FyX2ZyYW1lc19yZXF1ZXN0LnByb3RvGjRjYWtlbGFiL2FyZmxv",
            "d19ncnBjL3YxL3NhdmVfYXJfZnJhbWVzX3Jlc3BvbnNlLnByb3RvGj9jYWtl",
            "bGFiL2FyZmxvd19ncnBjL3YxL3NhdmVfc3luY2hyb25pemVkX2FyX2ZyYW1l",
            "X3JlcXVlc3QucHJvdG8aQGNha2VsYWIvYXJmbG93X2dycGMvdjEvc2F2ZV9z",
            "eW5jaHJvbml6ZWRfYXJfZnJhbWVfcmVzcG9uc2UucHJvdG8yhgcKDUFSRmxv",
            "d1NlcnZpY2USbAoNQ3JlYXRlU2Vzc2lvbhIsLmNha2VsYWIuYXJmbG93X2dy",
            "cGMudjEuQ3JlYXRlU2Vzc2lvblJlcXVlc3QaLS5jYWtlbGFiLmFyZmxvd19n",
            "cnBjLnYxLkNyZWF0ZVNlc3Npb25SZXNwb25zZRJsCg1EZWxldGVTZXNzaW9u",
            "EiwuY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5EZWxldGVTZXNzaW9uUmVxdWVz",
            "dBotLmNha2VsYWIuYXJmbG93X2dycGMudjEuRGVsZXRlU2Vzc2lvblJlc3Bv",
            "bnNlEmMKCkdldFNlc3Npb24SKS5jYWtlbGFiLmFyZmxvd19ncnBjLnYxLkdl",
            "dFNlc3Npb25SZXF1ZXN0GiouY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5HZXRT",
            "ZXNzaW9uUmVzcG9uc2USaQoMTGlzdFNlc3Npb25zEisuY2FrZWxhYi5hcmZs",
            "b3dfZ3JwYy52MS5MaXN0U2Vzc2lvbnNSZXF1ZXN0GiwuY2FrZWxhYi5hcmZs",
            "b3dfZ3JwYy52MS5MaXN0U2Vzc2lvbnNSZXNwb25zZRJmCgtKb2luU2Vzc2lv",
            "bhIqLmNha2VsYWIuYXJmbG93X2dycGMudjEuSm9pblNlc3Npb25SZXF1ZXN0",
            "GisuY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5Kb2luU2Vzc2lvblJlc3BvbnNl",
            "EmkKDExlYXZlU2Vzc2lvbhIrLmNha2VsYWIuYXJmbG93X2dycGMudjEuTGVh",
            "dmVTZXNzaW9uUmVxdWVzdBosLmNha2VsYWIuYXJmbG93X2dycGMudjEuTGVh",
            "dmVTZXNzaW9uUmVzcG9uc2USaQoMU2F2ZUFSRnJhbWVzEisuY2FrZWxhYi5h",
            "cmZsb3dfZ3JwYy52MS5TYXZlQVJGcmFtZXNSZXF1ZXN0GiwuY2FrZWxhYi5h",
            "cmZsb3dfZ3JwYy52MS5TYXZlQVJGcmFtZXNSZXNwb25zZRKKAQoXU2F2ZVN5",
            "bmNocm9uaXplZEFSRnJhbWUSNi5jYWtlbGFiLmFyZmxvd19ncnBjLnYxLlNh",
            "dmVTeW5jaHJvbml6ZWRBUkZyYW1lUmVxdWVzdBo3LmNha2VsYWIuYXJmbG93",
            "X2dycGMudjEuU2F2ZVN5bmNocm9uaXplZEFSRnJhbWVSZXNwb25zZUKnAQoa",
            "Y29tLmNha2VsYWIuYXJmbG93X2dycGMudjFCEkFyZmxvd1NlcnZpY2VQcm90",
            "b1ABogIDQ0FYqgIWQ2FrZUxhYi5BUkZsb3cuR3JwYy5WMcoCFUNha2VsYWJc",
            "QXJmbG93R3JwY1xWMeICIUNha2VsYWJcQXJmbG93R3JwY1xWMVxHUEJNZXRh",
            "ZGF0YeoCF0Nha2VsYWI6OkFyZmxvd0dycGM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CakeLab.ARFlow.Grpc.V1.CreateSessionRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.CreateSessionResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.DeleteSessionRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.DeleteSessionResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.GetSessionRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.GetSessionResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.JoinSessionRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.JoinSessionResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.LeaveSessionRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.LeaveSessionResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.ListSessionsRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.ListSessionsResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.SaveArFramesRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.SaveArFramesResponseReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.SaveSynchronizedArFrameRequestReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.SaveSynchronizedArFrameResponseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
