// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/ar_trackable.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/ar_trackable.proto</summary>
  public static partial class ArTrackableReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/ar_trackable.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ArTrackableReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiljYWtlbGFiL2FyZmxvd19ncnBjL3YxL2FyX3RyYWNrYWJsZS5wcm90bxIW",
            "Y2FrZWxhYi5hcmZsb3dfZ3JwYy52MRohY2FrZWxhYi9hcmZsb3dfZ3JwYy92",
            "MS9wb3NlLnByb3RvIrQDCgtBUlRyYWNrYWJsZRIwCgRwb3NlGAEgASgLMhwu",
            "Y2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5Qb3NlUgRwb3NlElIKDHRyYWNrYWJs",
            "ZV9pZBgCIAEoCzIvLmNha2VsYWIuYXJmbG93X2dycGMudjEuQVJUcmFja2Fi",
            "bGUuVHJhY2thYmxlSWRSC3RyYWNrYWJsZUlkElgKDnRyYWNraW5nX3N0YXRl",
            "GAMgASgOMjEuY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5BUlRyYWNrYWJsZS5U",
            "cmFja2luZ1N0YXRlUg10cmFja2luZ1N0YXRlGkEKC1RyYWNrYWJsZUlkEhgK",
            "CHN1Yl9pZF8xGAEgASgEUgZzdWJJZDESGAoIc3ViX2lkXzIYAiABKARSBnN1",
            "YklkMiKBAQoNVHJhY2tpbmdTdGF0ZRIeChpUUkFDS0lOR19TVEFURV9VTlNQ",
            "RUNJRklFRBAAEhoKFlRSQUNLSU5HX1NUQVRFX0xJTUlURUQQARIXChNUUkFD",
            "S0lOR19TVEFURV9OT05FEAISGwoXVFJBQ0tJTkdfU1RBVEVfVFJBQ0tJTkcQ",
            "A0KlAQoaY29tLmNha2VsYWIuYXJmbG93X2dycGMudjFCEEFyVHJhY2thYmxl",
            "UHJvdG9QAaICA0NBWKoCFkNha2VMYWIuQVJGbG93LkdycGMuVjHKAhVDYWtl",
            "bGFiXEFyZmxvd0dycGNcVjHiAiFDYWtlbGFiXEFyZmxvd0dycGNcVjFcR1BC",
            "TWV0YWRhdGHqAhdDYWtlbGFiOjpBcmZsb3dHcnBjOjpWMWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CakeLab.ARFlow.Grpc.V1.PoseReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.ARTrackable), global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Parser, new[]{ "Pose", "TrackableId", "TrackingState" }, null, new[]{ typeof(global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId), global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId.Parser, new[]{ "SubId1", "SubId2" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARFoundation.ARTrackable-2.html#UnityEngine_XR_ARFoundation_ARTrackable
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ARTrackable : pb::IMessage<ARTrackable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ARTrackable> _parser = new pb::MessageParser<ARTrackable>(() => new ARTrackable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ARTrackable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CakeLab.ARFlow.Grpc.V1.ArTrackableReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARTrackable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARTrackable(ARTrackable other) : this() {
      pose_ = other.pose_ != null ? other.pose_.Clone() : null;
      trackableId_ = other.trackableId_ != null ? other.trackableId_.Clone() : null;
      trackingState_ = other.trackingState_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ARTrackable Clone() {
      return new ARTrackable(this);
    }

    /// <summary>Field number for the "pose" field.</summary>
    public const int PoseFieldNumber = 1;
    private global::CakeLab.ARFlow.Grpc.V1.Pose pose_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Pose Pose {
      get { return pose_; }
      set {
        pose_ = value;
      }
    }

    /// <summary>Field number for the "trackable_id" field.</summary>
    public const int TrackableIdFieldNumber = 2;
    private global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId trackableId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId TrackableId {
      get { return trackableId_; }
      set {
        trackableId_ = value;
      }
    }

    /// <summary>Field number for the "tracking_state" field.</summary>
    public const int TrackingStateFieldNumber = 3;
    private global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState trackingState_ = global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState TrackingState {
      get { return trackingState_; }
      set {
        trackingState_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ARTrackable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ARTrackable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pose, other.Pose)) return false;
      if (!object.Equals(TrackableId, other.TrackableId)) return false;
      if (TrackingState != other.TrackingState) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (pose_ != null) hash ^= Pose.GetHashCode();
      if (trackableId_ != null) hash ^= TrackableId.GetHashCode();
      if (TrackingState != global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified) hash ^= TrackingState.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (pose_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pose);
      }
      if (trackableId_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrackableId);
      }
      if (TrackingState != global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TrackingState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (pose_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pose);
      }
      if (trackableId_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrackableId);
      }
      if (TrackingState != global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) TrackingState);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (pose_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pose);
      }
      if (trackableId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrackableId);
      }
      if (TrackingState != global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TrackingState);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ARTrackable other) {
      if (other == null) {
        return;
      }
      if (other.pose_ != null) {
        if (pose_ == null) {
          Pose = new global::CakeLab.ARFlow.Grpc.V1.Pose();
        }
        Pose.MergeFrom(other.Pose);
      }
      if (other.trackableId_ != null) {
        if (trackableId_ == null) {
          TrackableId = new global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId();
        }
        TrackableId.MergeFrom(other.TrackableId);
      }
      if (other.TrackingState != global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState.Unspecified) {
        TrackingState = other.TrackingState;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pose_ == null) {
              Pose = new global::CakeLab.ARFlow.Grpc.V1.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 18: {
            if (trackableId_ == null) {
              TrackableId = new global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId();
            }
            input.ReadMessage(TrackableId);
            break;
          }
          case 24: {
            TrackingState = (global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (pose_ == null) {
              Pose = new global::CakeLab.ARFlow.Grpc.V1.Pose();
            }
            input.ReadMessage(Pose);
            break;
          }
          case 18: {
            if (trackableId_ == null) {
              TrackableId = new global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackableId();
            }
            input.ReadMessage(TrackableId);
            break;
          }
          case 24: {
            TrackingState = (global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Types.TrackingState) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the ARTrackable message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.TrackingState.html
      /// </summary>
      public enum TrackingState {
        [pbr::OriginalName("TRACKING_STATE_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("TRACKING_STATE_LIMITED")] Limited = 1,
        [pbr::OriginalName("TRACKING_STATE_NONE")] None = 2,
        [pbr::OriginalName("TRACKING_STATE_TRACKING")] Tracking = 3,
      }

      /// <summary>
      ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.TrackableId.html
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class TrackableId : pb::IMessage<TrackableId>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<TrackableId> _parser = new pb::MessageParser<TrackableId>(() => new TrackableId());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<TrackableId> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::CakeLab.ARFlow.Grpc.V1.ARTrackable.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackableId() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackableId(TrackableId other) : this() {
          subId1_ = other.subId1_;
          subId2_ = other.subId2_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public TrackableId Clone() {
          return new TrackableId(this);
        }

        /// <summary>Field number for the "sub_id_1" field.</summary>
        public const int SubId1FieldNumber = 1;
        private ulong subId1_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong SubId1 {
          get { return subId1_; }
          set {
            subId1_ = value;
          }
        }

        /// <summary>Field number for the "sub_id_2" field.</summary>
        public const int SubId2FieldNumber = 2;
        private ulong subId2_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public ulong SubId2 {
          get { return subId2_; }
          set {
            subId2_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as TrackableId);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(TrackableId other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (SubId1 != other.SubId1) return false;
          if (SubId2 != other.SubId2) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (SubId1 != 0UL) hash ^= SubId1.GetHashCode();
          if (SubId2 != 0UL) hash ^= SubId2.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (SubId1 != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(SubId1);
          }
          if (SubId2 != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(SubId2);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (SubId1 != 0UL) {
            output.WriteRawTag(8);
            output.WriteUInt64(SubId1);
          }
          if (SubId2 != 0UL) {
            output.WriteRawTag(16);
            output.WriteUInt64(SubId2);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (SubId1 != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SubId1);
          }
          if (SubId2 != 0UL) {
            size += 1 + pb::CodedOutputStream.ComputeUInt64Size(SubId2);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(TrackableId other) {
          if (other == null) {
            return;
          }
          if (other.SubId1 != 0UL) {
            SubId1 = other.SubId1;
          }
          if (other.SubId2 != 0UL) {
            SubId2 = other.SubId2;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                SubId1 = input.ReadUInt64();
                break;
              }
              case 16: {
                SubId2 = input.ReadUInt64();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                SubId1 = input.ReadUInt64();
                break;
              }
              case 16: {
                SubId2 = input.ReadUInt64();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
