// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/intrinsics.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/intrinsics.proto</summary>
  public static partial class IntrinsicsReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/intrinsics.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IntrinsicsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidjYWtlbGFiL2FyZmxvd19ncnBjL3YxL2ludHJpbnNpY3MucHJvdG8SFmNh",
            "a2VsYWIuYXJmbG93X2dycGMudjEaJGNha2VsYWIvYXJmbG93X2dycGMvdjEv",
            "dmVjdG9yMi5wcm90bxooY2FrZWxhYi9hcmZsb3dfZ3JwYy92MS92ZWN0b3Iy",
            "X2ludC5wcm90bxokY2FrZWxhYi9hcmZsb3dfZ3JwYy92MS92ZWN0b3IzLnBy",
            "b3RvIt4BCgpJbnRyaW5zaWNzEkIKDGZvY2FsX2xlbmd0aBgBIAEoCzIfLmNh",
            "a2VsYWIuYXJmbG93X2dycGMudjEuVmVjdG9yMlILZm9jYWxMZW5ndGgSSAoP",
            "cHJpbmNpcGFsX3BvaW50GAIgASgLMh8uY2FrZWxhYi5hcmZsb3dfZ3JwYy52",
            "MS5WZWN0b3IyUg5wcmluY2lwYWxQb2ludBJCCgpyZXNvbHV0aW9uGAMgASgL",
            "MiIuY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5WZWN0b3IySW50UgpyZXNvbHV0",
            "aW9uQqQBChpjb20uY2FrZWxhYi5hcmZsb3dfZ3JwYy52MUIPSW50cmluc2lj",
            "c1Byb3RvUAGiAgNDQViqAhZDYWtlTGFiLkFSRmxvdy5HcnBjLlYxygIVQ2Fr",
            "ZWxhYlxBcmZsb3dHcnBjXFYx4gIhQ2FrZWxhYlxBcmZsb3dHcnBjXFYxXEdQ",
            "Qk1ldGFkYXRh6gIXQ2FrZWxhYjo6QXJmbG93R3JwYzo6VjFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CakeLab.ARFlow.Grpc.V1.Vector2Reflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.Vector2IntReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.Vector3Reflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.Intrinsics), global::CakeLab.ARFlow.Grpc.V1.Intrinsics.Parser, new[]{ "FocalLength", "PrincipalPoint", "Resolution" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.XRCameraIntrinsics.html
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Intrinsics : pb::IMessage<Intrinsics>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Intrinsics> _parser = new pb::MessageParser<Intrinsics>(() => new Intrinsics());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Intrinsics> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CakeLab.ARFlow.Grpc.V1.IntrinsicsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Intrinsics() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Intrinsics(Intrinsics other) : this() {
      focalLength_ = other.focalLength_ != null ? other.focalLength_.Clone() : null;
      principalPoint_ = other.principalPoint_ != null ? other.principalPoint_.Clone() : null;
      resolution_ = other.resolution_ != null ? other.resolution_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Intrinsics Clone() {
      return new Intrinsics(this);
    }

    /// <summary>Field number for the "focal_length" field.</summary>
    public const int FocalLengthFieldNumber = 1;
    private global::CakeLab.ARFlow.Grpc.V1.Vector2 focalLength_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Vector2 FocalLength {
      get { return focalLength_; }
      set {
        focalLength_ = value;
      }
    }

    /// <summary>Field number for the "principal_point" field.</summary>
    public const int PrincipalPointFieldNumber = 2;
    private global::CakeLab.ARFlow.Grpc.V1.Vector2 principalPoint_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Vector2 PrincipalPoint {
      get { return principalPoint_; }
      set {
        principalPoint_ = value;
      }
    }

    /// <summary>Field number for the "resolution" field.</summary>
    public const int ResolutionFieldNumber = 3;
    private global::CakeLab.ARFlow.Grpc.V1.Vector2Int resolution_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Vector2Int Resolution {
      get { return resolution_; }
      set {
        resolution_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Intrinsics);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Intrinsics other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(FocalLength, other.FocalLength)) return false;
      if (!object.Equals(PrincipalPoint, other.PrincipalPoint)) return false;
      if (!object.Equals(Resolution, other.Resolution)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (focalLength_ != null) hash ^= FocalLength.GetHashCode();
      if (principalPoint_ != null) hash ^= PrincipalPoint.GetHashCode();
      if (resolution_ != null) hash ^= Resolution.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (focalLength_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FocalLength);
      }
      if (principalPoint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PrincipalPoint);
      }
      if (resolution_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Resolution);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (focalLength_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(FocalLength);
      }
      if (principalPoint_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PrincipalPoint);
      }
      if (resolution_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Resolution);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (focalLength_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FocalLength);
      }
      if (principalPoint_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PrincipalPoint);
      }
      if (resolution_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Resolution);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Intrinsics other) {
      if (other == null) {
        return;
      }
      if (other.focalLength_ != null) {
        if (focalLength_ == null) {
          FocalLength = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
        }
        FocalLength.MergeFrom(other.FocalLength);
      }
      if (other.principalPoint_ != null) {
        if (principalPoint_ == null) {
          PrincipalPoint = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
        }
        PrincipalPoint.MergeFrom(other.PrincipalPoint);
      }
      if (other.resolution_ != null) {
        if (resolution_ == null) {
          Resolution = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
        }
        Resolution.MergeFrom(other.Resolution);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (focalLength_ == null) {
              FocalLength = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
            }
            input.ReadMessage(FocalLength);
            break;
          }
          case 18: {
            if (principalPoint_ == null) {
              PrincipalPoint = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
            }
            input.ReadMessage(PrincipalPoint);
            break;
          }
          case 26: {
            if (resolution_ == null) {
              Resolution = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
            }
            input.ReadMessage(Resolution);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (focalLength_ == null) {
              FocalLength = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
            }
            input.ReadMessage(FocalLength);
            break;
          }
          case 18: {
            if (principalPoint_ == null) {
              PrincipalPoint = new global::CakeLab.ARFlow.Grpc.V1.Vector2();
            }
            input.ReadMessage(PrincipalPoint);
            break;
          }
          case 26: {
            if (resolution_ == null) {
              Resolution = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
            }
            input.ReadMessage(Resolution);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
