// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/intrinsic_request.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/intrinsic_request.proto</summary>
  public static partial class IntrinsicRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/intrinsic_request.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IntrinsicRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5jYWtlbGFiL2FyZmxvd19ncnBjL3YxL2ludHJpbnNpY19yZXF1ZXN0LnBy",
            "b3RvEhZjYWtlbGFiLmFyZmxvd19ncnBjLnYxGiZjYWtlbGFiL2FyZmxvd19n",
            "cnBjL3YxL2ludHJpbnNpYy5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3RpbWVz",
            "dGFtcC5wcm90bxojY2FrZWxhYi9hcmZsb3dfZ3JwYy92MS9kZXZpY2UucHJv",
            "dG8aJGNha2VsYWIvYXJmbG93X2dycGMvdjEvc2Vzc2lvbi5wcm90byKWAgoQ",
            "SW50cmluc2ljUmVxdWVzdBJCCgpzZXNzaW9uX2lkGAEgASgLMiMuY2FrZWxh",
            "Yi5hcmZsb3dfZ3JwYy52MS5TZXNzaW9uVXVpZFIJc2Vzc2lvbklkEjYKBmRl",
            "dmljZRgCIAEoCzIeLmNha2VsYWIuYXJmbG93X2dycGMudjEuRGV2aWNlUgZk",
            "ZXZpY2USRQoQZGV2aWNlX3RpbWVzdGFtcBgDIAEoCzIaLmdvb2dsZS5wcm90",
            "b2J1Zi5UaW1lc3RhbXBSD2RldmljZVRpbWVzdGFtcBI/CglpbnRyaW5zaWMY",
            "BCABKAsyIS5jYWtlbGFiLmFyZmxvd19ncnBjLnYxLkludHJpbnNpY1IJaW50",
            "cmluc2ljQqoBChpjb20uY2FrZWxhYi5hcmZsb3dfZ3JwYy52MUIVSW50cmlu",
            "c2ljUmVxdWVzdFByb3RvUAGiAgNDQViqAhZDYWtlTGFiLkFSRmxvdy5HcnBj",
            "LlYxygIVQ2FrZWxhYlxBcmZsb3dHcnBjXFYx4gIhQ2FrZWxhYlxBcmZsb3dH",
            "cnBjXFYxXEdQQk1ldGFkYXRh6gIXQ2FrZWxhYjo6QXJmbG93R3JwYzo6VjFi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CakeLab.ARFlow.Grpc.V1.IntrinsicReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.DeviceReflection.Descriptor, global::CakeLab.ARFlow.Grpc.V1.SessionReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.IntrinsicRequest), global::CakeLab.ARFlow.Grpc.V1.IntrinsicRequest.Parser, new[]{ "SessionId", "Device", "DeviceTimestamp", "Intrinsic" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARFoundation.ARPlane.html#UnityEngine_XR_ARFoundation_ARPlane
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class IntrinsicRequest : pb::IMessage<IntrinsicRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<IntrinsicRequest> _parser = new pb::MessageParser<IntrinsicRequest>(() => new IntrinsicRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<IntrinsicRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CakeLab.ARFlow.Grpc.V1.IntrinsicRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntrinsicRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntrinsicRequest(IntrinsicRequest other) : this() {
      sessionId_ = other.sessionId_ != null ? other.sessionId_.Clone() : null;
      device_ = other.device_ != null ? other.device_.Clone() : null;
      deviceTimestamp_ = other.deviceTimestamp_ != null ? other.deviceTimestamp_.Clone() : null;
      intrinsic_ = other.intrinsic_ != null ? other.intrinsic_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public IntrinsicRequest Clone() {
      return new IntrinsicRequest(this);
    }

    /// <summary>Field number for the "session_id" field.</summary>
    public const int SessionIdFieldNumber = 1;
    private global::CakeLab.ARFlow.Grpc.V1.SessionUuid sessionId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.SessionUuid SessionId {
      get { return sessionId_; }
      set {
        sessionId_ = value;
      }
    }

    /// <summary>Field number for the "device" field.</summary>
    public const int DeviceFieldNumber = 2;
    private global::CakeLab.ARFlow.Grpc.V1.Device device_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Device Device {
      get { return device_; }
      set {
        device_ = value;
      }
    }

    /// <summary>Field number for the "device_timestamp" field.</summary>
    public const int DeviceTimestampFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp deviceTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DeviceTimestamp {
      get { return deviceTimestamp_; }
      set {
        deviceTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "intrinsic" field.</summary>
    public const int IntrinsicFieldNumber = 4;
    private global::CakeLab.ARFlow.Grpc.V1.Intrinsic intrinsic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Intrinsic Intrinsic {
      get { return intrinsic_; }
      set {
        intrinsic_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as IntrinsicRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(IntrinsicRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(SessionId, other.SessionId)) return false;
      if (!object.Equals(Device, other.Device)) return false;
      if (!object.Equals(DeviceTimestamp, other.DeviceTimestamp)) return false;
      if (!object.Equals(Intrinsic, other.Intrinsic)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (sessionId_ != null) hash ^= SessionId.GetHashCode();
      if (device_ != null) hash ^= Device.GetHashCode();
      if (deviceTimestamp_ != null) hash ^= DeviceTimestamp.GetHashCode();
      if (intrinsic_ != null) hash ^= Intrinsic.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (sessionId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SessionId);
      }
      if (device_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Device);
      }
      if (deviceTimestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DeviceTimestamp);
      }
      if (intrinsic_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Intrinsic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (sessionId_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(SessionId);
      }
      if (device_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Device);
      }
      if (deviceTimestamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DeviceTimestamp);
      }
      if (intrinsic_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Intrinsic);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (sessionId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SessionId);
      }
      if (device_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Device);
      }
      if (deviceTimestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeviceTimestamp);
      }
      if (intrinsic_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Intrinsic);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(IntrinsicRequest other) {
      if (other == null) {
        return;
      }
      if (other.sessionId_ != null) {
        if (sessionId_ == null) {
          SessionId = new global::CakeLab.ARFlow.Grpc.V1.SessionUuid();
        }
        SessionId.MergeFrom(other.SessionId);
      }
      if (other.device_ != null) {
        if (device_ == null) {
          Device = new global::CakeLab.ARFlow.Grpc.V1.Device();
        }
        Device.MergeFrom(other.Device);
      }
      if (other.deviceTimestamp_ != null) {
        if (deviceTimestamp_ == null) {
          DeviceTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DeviceTimestamp.MergeFrom(other.DeviceTimestamp);
      }
      if (other.intrinsic_ != null) {
        if (intrinsic_ == null) {
          Intrinsic = new global::CakeLab.ARFlow.Grpc.V1.Intrinsic();
        }
        Intrinsic.MergeFrom(other.Intrinsic);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (sessionId_ == null) {
              SessionId = new global::CakeLab.ARFlow.Grpc.V1.SessionUuid();
            }
            input.ReadMessage(SessionId);
            break;
          }
          case 18: {
            if (device_ == null) {
              Device = new global::CakeLab.ARFlow.Grpc.V1.Device();
            }
            input.ReadMessage(Device);
            break;
          }
          case 26: {
            if (deviceTimestamp_ == null) {
              DeviceTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeviceTimestamp);
            break;
          }
          case 34: {
            if (intrinsic_ == null) {
              Intrinsic = new global::CakeLab.ARFlow.Grpc.V1.Intrinsic();
            }
            input.ReadMessage(Intrinsic);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (sessionId_ == null) {
              SessionId = new global::CakeLab.ARFlow.Grpc.V1.SessionUuid();
            }
            input.ReadMessage(SessionId);
            break;
          }
          case 18: {
            if (device_ == null) {
              Device = new global::CakeLab.ARFlow.Grpc.V1.Device();
            }
            input.ReadMessage(Device);
            break;
          }
          case 26: {
            if (deviceTimestamp_ == null) {
              DeviceTimestamp = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(DeviceTimestamp);
            break;
          }
          case 34: {
            if (intrinsic_ == null) {
              Intrinsic = new global::CakeLab.ARFlow.Grpc.V1.Intrinsic();
            }
            input.ReadMessage(Intrinsic);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
