// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/timeline.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/timeline.proto</summary>
  public static partial class TimelineReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/timeline.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TimelineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVjYWtlbGFiL2FyZmxvd19ncnBjL3YxL3RpbWVsaW5lLnByb3RvEhZjYWtl",
            "bGFiLmFyZmxvd19ncnBjLnYxKmEKCFRpbWVsaW5lEhgKFFRJTUVMSU5FX1VO",
            "U1BFQ0lGSUVEEAASHQoZVElNRUxJTkVfREVWSUNFX1RJTUVTVEFNUBABEhwK",
            "GFRJTUVMSU5FX0lNQUdFX1RJTUVTVEFNUBACQqIBChpjb20uY2FrZWxhYi5h",
            "cmZsb3dfZ3JwYy52MUINVGltZWxpbmVQcm90b1ABogIDQ0FYqgIWQ2FrZUxh",
            "Yi5BUkZsb3cuR3JwYy5WMcoCFUNha2VsYWJcQXJmbG93R3JwY1xWMeICIUNh",
            "a2VsYWJcQXJmbG93R3JwY1xWMVxHUEJNZXRhZGF0YeoCF0Nha2VsYWI6OkFy",
            "Zmxvd0dycGM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::CakeLab.ARFlow.Grpc.V1.Timeline), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Timeline {
    [pbr::OriginalName("TIMELINE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("TIMELINE_DEVICE_TIMESTAMP")] DeviceTimestamp = 1,
    [pbr::OriginalName("TIMELINE_IMAGE_TIMESTAMP")] ImageTimestamp = 2,
  }

  #endregion

}

#endregion Designer generated code
