// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cakelab/arflow_grpc/v1/xr_cpu_image.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace CakeLab.ARFlow.Grpc.V1 {

  /// <summary>Holder for reflection information generated from cakelab/arflow_grpc/v1/xr_cpu_image.proto</summary>
  public static partial class XrCpuImageReflection {

    #region Descriptor
    /// <summary>File descriptor for cakelab/arflow_grpc/v1/xr_cpu_image.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static XrCpuImageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiljYWtlbGFiL2FyZmxvd19ncnBjL3YxL3hyX2NwdV9pbWFnZS5wcm90bxIW",
            "Y2FrZWxhYi5hcmZsb3dfZ3JwYy52MRooY2FrZWxhYi9hcmZsb3dfZ3JwYy92",
            "MS92ZWN0b3IyX2ludC5wcm90byKLBQoKWFJDcHVJbWFnZRJCCgpkaW1lbnNp",
            "b25zGAEgASgLMiIuY2FrZWxhYi5hcmZsb3dfZ3JwYy52MS5WZWN0b3IySW50",
            "UgpkaW1lbnNpb25zEkEKBmZvcm1hdBgCIAEoDjIpLmNha2VsYWIuYXJmbG93",
            "X2dycGMudjEuWFJDcHVJbWFnZS5Gb3JtYXRSBmZvcm1hdBIcCgl0aW1lc3Rh",
            "bXAYAyABKAFSCXRpbWVzdGFtcBJACgZwbGFuZXMYBCADKAsyKC5jYWtlbGFi",
            "LmFyZmxvd19ncnBjLnYxLlhSQ3B1SW1hZ2UuUGxhbmVSBnBsYW5lcxpdCgVQ",
            "bGFuZRIdCgpyb3dfc3RyaWRlGAEgASgFUglyb3dTdHJpZGUSIQoMcGl4ZWxf",
            "c3RyaWRlGAIgASgFUgtwaXhlbFN0cmlkZRISCgRkYXRhGAMgASgMUgRkYXRh",
            "IrYCCgZGb3JtYXQSFgoSRk9STUFUX1VOU1BFQ0lGSUVEEAASHgoaRk9STUFU",
            "X0FORFJPSURfWVVWXzQyMF84ODgQARIwCixGT1JNQVRfSU9TX1lQX0NCQ1Jf",
            "NDIwXzhCSV9QTEFOQVJfRlVMTF9SQU5HRRACEhcKE0ZPUk1BVF9ERVBUSEZM",
            "T0FUMzIQBBIWChJGT1JNQVRfREVQVEhVSU5UMTYQBRIZChVGT1JNQVRfT05F",
            "Q09NUE9ORU5UMzIQBhIRCg1GT1JNQVRfQVJHQjMyEAcSEQoNRk9STUFUX1JH",
            "QkEzMhAIEhEKDUZPUk1BVF9CR1JBMzIQCRIQCgxGT1JNQVRfUkdCMjQQChIV",
            "ChFGT1JNQVRfSlBFR19SR0IyNBALEhQKEEZPUk1BVF9QTkdfUkdCMjQQDEKk",
            "AQoaY29tLmNha2VsYWIuYXJmbG93X2dycGMudjFCD1hyQ3B1SW1hZ2VQcm90",
            "b1ABogIDQ0FYqgIWQ2FrZUxhYi5BUkZsb3cuR3JwYy5WMcoCFUNha2VsYWJc",
            "QXJmbG93R3JwY1xWMeICIUNha2VsYWJcQXJmbG93R3JwY1xWMVxHUEJNZXRh",
            "ZGF0YeoCF0Nha2VsYWI6OkFyZmxvd0dycGM6OlYxYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::CakeLab.ARFlow.Grpc.V1.Vector2IntReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.XRCpuImage), global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Parser, new[]{ "Dimensions", "Format", "Timestamp", "Planes" }, null, new[]{ typeof(global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane), global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane.Parser, new[]{ "RowStride", "PixelStride", "Data" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.XRCpuImage.html
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class XRCpuImage : pb::IMessage<XRCpuImage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<XRCpuImage> _parser = new pb::MessageParser<XRCpuImage>(() => new XRCpuImage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<XRCpuImage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::CakeLab.ARFlow.Grpc.V1.XrCpuImageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public XRCpuImage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public XRCpuImage(XRCpuImage other) : this() {
      dimensions_ = other.dimensions_ != null ? other.dimensions_.Clone() : null;
      format_ = other.format_;
      timestamp_ = other.timestamp_;
      planes_ = other.planes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public XRCpuImage Clone() {
      return new XRCpuImage(this);
    }

    /// <summary>Field number for the "dimensions" field.</summary>
    public const int DimensionsFieldNumber = 1;
    private global::CakeLab.ARFlow.Grpc.V1.Vector2Int dimensions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.Vector2Int Dimensions {
      get { return dimensions_; }
      set {
        dimensions_ = value;
      }
    }

    /// <summary>Field number for the "format" field.</summary>
    public const int FormatFieldNumber = 2;
    private global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format format_ = global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format Format {
      get { return format_; }
      set {
        format_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 3;
    private double timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "planes" field.</summary>
    public const int PlanesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane> _repeated_planes_codec
        = pb::FieldCodec.ForMessage(34, global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane.Parser);
    private readonly pbc::RepeatedField<global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane> planes_ = new pbc::RepeatedField<global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Plane> Planes {
      get { return planes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as XRCpuImage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(XRCpuImage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Dimensions, other.Dimensions)) return false;
      if (Format != other.Format) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timestamp, other.Timestamp)) return false;
      if(!planes_.Equals(other.planes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (dimensions_ != null) hash ^= Dimensions.GetHashCode();
      if (Format != global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified) hash ^= Format.GetHashCode();
      if (Timestamp != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timestamp);
      hash ^= planes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (dimensions_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Dimensions);
      }
      if (Format != global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Format);
      }
      if (Timestamp != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Timestamp);
      }
      planes_.WriteTo(output, _repeated_planes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (dimensions_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Dimensions);
      }
      if (Format != global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Format);
      }
      if (Timestamp != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Timestamp);
      }
      planes_.WriteTo(ref output, _repeated_planes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (dimensions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Dimensions);
      }
      if (Format != global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Format);
      }
      if (Timestamp != 0D) {
        size += 1 + 8;
      }
      size += planes_.CalculateSize(_repeated_planes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(XRCpuImage other) {
      if (other == null) {
        return;
      }
      if (other.dimensions_ != null) {
        if (dimensions_ == null) {
          Dimensions = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
        }
        Dimensions.MergeFrom(other.Dimensions);
      }
      if (other.Format != global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format.Unspecified) {
        Format = other.Format;
      }
      if (other.Timestamp != 0D) {
        Timestamp = other.Timestamp;
      }
      planes_.Add(other.planes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (dimensions_ == null) {
              Dimensions = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
            }
            input.ReadMessage(Dimensions);
            break;
          }
          case 16: {
            Format = (global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format) input.ReadEnum();
            break;
          }
          case 25: {
            Timestamp = input.ReadDouble();
            break;
          }
          case 34: {
            planes_.AddEntriesFrom(input, _repeated_planes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (dimensions_ == null) {
              Dimensions = new global::CakeLab.ARFlow.Grpc.V1.Vector2Int();
            }
            input.ReadMessage(Dimensions);
            break;
          }
          case 16: {
            Format = (global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Types.Format) input.ReadEnum();
            break;
          }
          case 25: {
            Timestamp = input.ReadDouble();
            break;
          }
          case 34: {
            planes_.AddEntriesFrom(ref input, _repeated_planes_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the XRCpuImage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.XRCpuImage.Format.html
      /// </summary>
      public enum Format {
        [pbr::OriginalName("FORMAT_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// @exclude The number in each field should match the enum XRCpuImage.Format for more convenient conversion.
        /// </summary>
        [pbr::OriginalName("FORMAT_ANDROID_YUV_420_888")] AndroidYuv420888 = 1,
        [pbr::OriginalName("FORMAT_IOS_YP_CBCR_420_8BI_PLANAR_FULL_RANGE")] IosYpCbcr4208BiPlanarFullRange = 2,
        /// <summary>
        /// @exclude FORMAT_ONECOMPONENT8 = 3;
        /// </summary>
        [pbr::OriginalName("FORMAT_DEPTHFLOAT32")] Depthfloat32 = 4,
        /// <summary>
        ///&#x2F; Android
        /// </summary>
        [pbr::OriginalName("FORMAT_DEPTHUINT16")] Depthuint16 = 5,
        [pbr::OriginalName("FORMAT_ONECOMPONENT32")] Onecomponent32 = 6,
        [pbr::OriginalName("FORMAT_ARGB32")] Argb32 = 7,
        [pbr::OriginalName("FORMAT_RGBA32")] Rgba32 = 8,
        [pbr::OriginalName("FORMAT_BGRA32")] Bgra32 = 9,
        [pbr::OriginalName("FORMAT_RGB24")] Rgb24 = 10,
        [pbr::OriginalName("FORMAT_JPEG_RGB24")] JpegRgb24 = 11,
        [pbr::OriginalName("FORMAT_PNG_RGB24")] PngRgb24 = 12,
      }

      /// <summary>
      ///&#x2F; https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@6.0/api/UnityEngine.XR.ARSubsystems.XRCpuImage.Plane.html
      /// </summary>
      [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
      public sealed partial class Plane : pb::IMessage<Plane>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Plane> _parser = new pb::MessageParser<Plane>(() => new Plane());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Plane> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::CakeLab.ARFlow.Grpc.V1.XRCpuImage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Plane() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Plane(Plane other) : this() {
          rowStride_ = other.rowStride_;
          pixelStride_ = other.pixelStride_;
          data_ = other.data_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Plane Clone() {
          return new Plane(this);
        }

        /// <summary>Field number for the "row_stride" field.</summary>
        public const int RowStrideFieldNumber = 1;
        private int rowStride_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int RowStride {
          get { return rowStride_; }
          set {
            rowStride_ = value;
          }
        }

        /// <summary>Field number for the "pixel_stride" field.</summary>
        public const int PixelStrideFieldNumber = 2;
        private int pixelStride_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int PixelStride {
          get { return pixelStride_; }
          set {
            pixelStride_ = value;
          }
        }

        /// <summary>Field number for the "data" field.</summary>
        public const int DataFieldNumber = 3;
        private pb::ByteString data_ = pb::ByteString.Empty;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pb::ByteString Data {
          get { return data_; }
          set {
            data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Plane);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Plane other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (RowStride != other.RowStride) return false;
          if (PixelStride != other.PixelStride) return false;
          if (Data != other.Data) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (RowStride != 0) hash ^= RowStride.GetHashCode();
          if (PixelStride != 0) hash ^= PixelStride.GetHashCode();
          if (Data.Length != 0) hash ^= Data.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (RowStride != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(RowStride);
          }
          if (PixelStride != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PixelStride);
          }
          if (Data.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Data);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (RowStride != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(RowStride);
          }
          if (PixelStride != 0) {
            output.WriteRawTag(16);
            output.WriteInt32(PixelStride);
          }
          if (Data.Length != 0) {
            output.WriteRawTag(26);
            output.WriteBytes(Data);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (RowStride != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(RowStride);
          }
          if (PixelStride != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(PixelStride);
          }
          if (Data.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Plane other) {
          if (other == null) {
            return;
          }
          if (other.RowStride != 0) {
            RowStride = other.RowStride;
          }
          if (other.PixelStride != 0) {
            PixelStride = other.PixelStride;
          }
          if (other.Data.Length != 0) {
            Data = other.Data;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                RowStride = input.ReadInt32();
                break;
              }
              case 16: {
                PixelStride = input.ReadInt32();
                break;
              }
              case 26: {
                Data = input.ReadBytes();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
          if ((tag & 7) == 4) {
            // Abort on any end group tag.
            return;
          }
          switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 8: {
                RowStride = input.ReadInt32();
                break;
              }
              case 16: {
                PixelStride = input.ReadInt32();
                break;
              }
              case 26: {
                Data = input.ReadBytes();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
