# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arflow_grpc import service_pb2 as arflow__grpc_dot_service__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arflow_grpc/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ARFlowServiceStub(object):
    """The ARFlow service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/arflow.v1.ARFlowService/RegisterClient',
                request_serializer=arflow__grpc_dot_service__pb2.RegisterClientRequest.SerializeToString,
                response_deserializer=arflow__grpc_dot_service__pb2.RegisterClientResponse.FromString,
                _registered_method=True)
        self.ProcessFrame = channel.unary_unary(
                '/arflow.v1.ARFlowService/ProcessFrame',
                request_serializer=arflow__grpc_dot_service__pb2.ProcessFrameRequest.SerializeToString,
                response_deserializer=arflow__grpc_dot_service__pb2.ProcessFrameResponse.FromString,
                _registered_method=True)


class ARFlowServiceServicer(object):
    """The ARFlow service definition.
    """

    def RegisterClient(self, request, context):
        """Registers a client with the given specifications.

        The client is registered with the server and is assigned a unique identifier.
        The client can then send data frames to the server using the assigned identifier.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFrame(self, request, context):
        """Accepts a data frame from a client, returning an acknowledgment.

        Errors:
        - NOT_FOUND: If the client configuration is not found.
        - INVALID_ARGUMENT: If the color data type is not recognized or the depth data type 
        is not recognized or if the request's data cannot be decoded (e.g., corrupted or invalid data).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ARFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=arflow__grpc_dot_service__pb2.RegisterClientRequest.FromString,
                    response_serializer=arflow__grpc_dot_service__pb2.RegisterClientResponse.SerializeToString,
            ),
            'ProcessFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFrame,
                    request_deserializer=arflow__grpc_dot_service__pb2.ProcessFrameRequest.FromString,
                    response_serializer=arflow__grpc_dot_service__pb2.ProcessFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arflow.v1.ARFlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arflow.v1.ARFlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ARFlowService(object):
    """The ARFlow service definition.
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arflow.v1.ARFlowService/RegisterClient',
            arflow__grpc_dot_service__pb2.RegisterClientRequest.SerializeToString,
            arflow__grpc_dot_service__pb2.RegisterClientResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arflow.v1.ARFlowService/ProcessFrame',
            arflow__grpc_dot_service__pb2.ProcessFrameRequest.SerializeToString,
            arflow__grpc_dot_service__pb2.ProcessFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
