# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from arflow import service_pb2 as arflow_dot_service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arflow/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ARFlowServiceStub(object):
    """The ARFlowService service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register = channel.unary_unary(
                '/ARFlowService/register',
                request_serializer=arflow_dot_service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=arflow_dot_service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.data_frame = channel.unary_unary(
                '/ARFlowService/data_frame',
                request_serializer=arflow_dot_service__pb2.DataFrameRequest.SerializeToString,
                response_deserializer=arflow_dot_service__pb2.DataFrameResponse.FromString,
                _registered_method=True)


class ARFlowServiceServicer(object):
    """The ARFlowService service definition.
    """

    def register(self, request, context):
        """Registers a device with the given specifications.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def data_frame(self, request, context):
        """Sends a data frame from a device.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ARFlowServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register': grpc.unary_unary_rpc_method_handler(
                    servicer.register,
                    request_deserializer=arflow_dot_service__pb2.RegisterRequest.FromString,
                    response_serializer=arflow_dot_service__pb2.RegisterResponse.SerializeToString,
            ),
            'data_frame': grpc.unary_unary_rpc_method_handler(
                    servicer.data_frame,
                    request_deserializer=arflow_dot_service__pb2.DataFrameRequest.FromString,
                    response_serializer=arflow_dot_service__pb2.DataFrameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ARFlowService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ARFlowService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ARFlowService(object):
    """The ARFlowService service definition.
    """

    @staticmethod
    def register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ARFlowService/register',
            arflow_dot_service__pb2.RegisterRequest.SerializeToString,
            arflow_dot_service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def data_frame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ARFlowService/data_frame',
            arflow_dot_service__pb2.DataFrameRequest.SerializeToString,
            arflow_dot_service__pb2.DataFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
