# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cakelab/arflow_grpc/v1/ar_trackable.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'cakelab/arflow_grpc/v1/ar_trackable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cakelab.arflow_grpc.v1 import pose_pb2 as cakelab_dot_arflow__grpc_dot_v1_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)cakelab/arflow_grpc/v1/ar_trackable.proto\x12\x16\x63\x61kelab.arflow_grpc.v1\x1a!cakelab/arflow_grpc/v1/pose.proto\"\xb4\x03\n\x0b\x41RTrackable\x12\x30\n\x04pose\x18\x01 \x01(\x0b\x32\x1c.cakelab.arflow_grpc.v1.PoseR\x04pose\x12R\n\x0ctrackable_id\x18\x02 \x01(\x0b\x32/.cakelab.arflow_grpc.v1.ARTrackable.TrackableIdR\x0btrackableId\x12X\n\x0etracking_state\x18\x03 \x01(\x0e\x32\x31.cakelab.arflow_grpc.v1.ARTrackable.TrackingStateR\rtrackingState\x1a\x41\n\x0bTrackableId\x12\x18\n\x08sub_id_1\x18\x01 \x01(\x04R\x06subId1\x12\x18\n\x08sub_id_2\x18\x02 \x01(\x04R\x06subId2\"\x81\x01\n\rTrackingState\x12\x1e\n\x1aTRACKING_STATE_UNSPECIFIED\x10\x00\x12\x1a\n\x16TRACKING_STATE_LIMITED\x10\x01\x12\x17\n\x13TRACKING_STATE_NONE\x10\x02\x12\x1b\n\x17TRACKING_STATE_TRACKING\x10\x03\x42\xa5\x01\n\x1a\x63om.cakelab.arflow_grpc.v1B\x10\x41rTrackableProtoP\x01\xa2\x02\x03\x43\x41X\xaa\x02\x16\x43\x61keLab.ARFlow.Grpc.V1\xca\x02\x15\x43\x61kelab\\ArflowGrpc\\V1\xe2\x02!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\xea\x02\x17\x43\x61kelab::ArflowGrpc::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cakelab.arflow_grpc.v1.ar_trackable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.cakelab.arflow_grpc.v1B\020ArTrackableProtoP\001\242\002\003CAX\252\002\026CakeLab.ARFlow.Grpc.V1\312\002\025Cakelab\\ArflowGrpc\\V1\342\002!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\352\002\027Cakelab::ArflowGrpc::V1'
  _globals['_ARTRACKABLE']._serialized_start=105
  _globals['_ARTRACKABLE']._serialized_end=541
  _globals['_ARTRACKABLE_TRACKABLEID']._serialized_start=344
  _globals['_ARTRACKABLE_TRACKABLEID']._serialized_end=409
  _globals['_ARTRACKABLE_TRACKINGSTATE']._serialized_start=412
  _globals['_ARTRACKABLE_TRACKINGSTATE']._serialized_end=541
# @@protoc_insertion_point(module_scope)
