from cakelab.arflow_grpc.v1 import create_session_request_pb2 as _create_session_request_pb2
from cakelab.arflow_grpc.v1 import create_session_response_pb2 as _create_session_response_pb2
from cakelab.arflow_grpc.v1 import delete_session_request_pb2 as _delete_session_request_pb2
from cakelab.arflow_grpc.v1 import delete_session_response_pb2 as _delete_session_response_pb2
from cakelab.arflow_grpc.v1 import get_session_request_pb2 as _get_session_request_pb2
from cakelab.arflow_grpc.v1 import get_session_response_pb2 as _get_session_response_pb2
from cakelab.arflow_grpc.v1 import join_session_request_pb2 as _join_session_request_pb2
from cakelab.arflow_grpc.v1 import join_session_response_pb2 as _join_session_response_pb2
from cakelab.arflow_grpc.v1 import leave_session_request_pb2 as _leave_session_request_pb2
from cakelab.arflow_grpc.v1 import leave_session_response_pb2 as _leave_session_response_pb2
from cakelab.arflow_grpc.v1 import list_sessions_request_pb2 as _list_sessions_request_pb2
from cakelab.arflow_grpc.v1 import list_sessions_response_pb2 as _list_sessions_response_pb2
from cakelab.arflow_grpc.v1 import save_ar_frames_request_pb2 as _save_ar_frames_request_pb2
from cakelab.arflow_grpc.v1 import save_ar_frames_response_pb2 as _save_ar_frames_response_pb2
from cakelab.arflow_grpc.v1 import save_synchronized_ar_frame_request_pb2 as _save_synchronized_ar_frame_request_pb2
from cakelab.arflow_grpc.v1 import save_synchronized_ar_frame_response_pb2 as _save_synchronized_ar_frame_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
