# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cakelab/arflow_grpc/v1/join_session_response.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'cakelab/arflow_grpc/v1/join_session_response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cakelab.arflow_grpc.v1 import session_pb2 as cakelab_dot_arflow__grpc_dot_v1_dot_session__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2cakelab/arflow_grpc/v1/join_session_response.proto\x12\x16\x63\x61kelab.arflow_grpc.v1\x1a$cakelab/arflow_grpc/v1/session.proto\"P\n\x13JoinSessionResponse\x12\x39\n\x07session\x18\x01 \x01(\x0b\x32\x1f.cakelab.arflow_grpc.v1.SessionR\x07sessionB\xad\x01\n\x1a\x63om.cakelab.arflow_grpc.v1B\x18JoinSessionResponseProtoP\x01\xa2\x02\x03\x43\x41X\xaa\x02\x16\x43\x61keLab.ARFlow.Grpc.V1\xca\x02\x15\x43\x61kelab\\ArflowGrpc\\V1\xe2\x02!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\xea\x02\x17\x43\x61kelab::ArflowGrpc::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cakelab.arflow_grpc.v1.join_session_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.cakelab.arflow_grpc.v1B\030JoinSessionResponseProtoP\001\242\002\003CAX\252\002\026CakeLab.ARFlow.Grpc.V1\312\002\025Cakelab\\ArflowGrpc\\V1\342\002!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\352\002\027Cakelab::ArflowGrpc::V1'
  _globals['_JOINSESSIONRESPONSE']._serialized_start=116
  _globals['_JOINSESSIONRESPONSE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
