# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cakelab/arflow_grpc/v1/pose_frame.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'cakelab/arflow_grpc/v1/pose_frame.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cakelab.arflow_grpc.v1 import pose_pb2 as cakelab_dot_arflow__grpc_dot_v1_dot_pose__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'cakelab/arflow_grpc/v1/pose_frame.proto\x12\x16\x63\x61kelab.arflow_grpc.v1\x1a!cakelab/arflow_grpc/v1/pose.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x84\x01\n\tPoseFrame\x12\x45\n\x10\x64\x65vice_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x0f\x64\x65viceTimestamp\x12\x30\n\x04pose\x18\x02 \x01(\x0b\x32\x1c.cakelab.arflow_grpc.v1.PoseR\x04poseB\xa3\x01\n\x1a\x63om.cakelab.arflow_grpc.v1B\x0ePoseFrameProtoP\x01\xa2\x02\x03\x43\x41X\xaa\x02\x16\x43\x61keLab.ARFlow.Grpc.V1\xca\x02\x15\x43\x61kelab\\ArflowGrpc\\V1\xe2\x02!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\xea\x02\x17\x43\x61kelab::ArflowGrpc::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cakelab.arflow_grpc.v1.pose_frame_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.cakelab.arflow_grpc.v1B\016PoseFrameProtoP\001\242\002\003CAX\252\002\026CakeLab.ARFlow.Grpc.V1\312\002\025Cakelab\\ArflowGrpc\\V1\342\002!Cakelab\\ArflowGrpc\\V1\\GPBMetadata\352\002\027Cakelab::ArflowGrpc::V1'
  _globals['_POSEFRAME']._serialized_start=136
  _globals['_POSEFRAME']._serialized_end=268
# @@protoc_insertion_point(module_scope)
